env:
  browser: true
  es2020: true
extends:
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  max-len: 
    - error
    - "code": 111
  object-curly-spacing: 
    - error
    - "always"
  indent:
    - error
    - 2
